import pandas as pd
import streamlit as st
import random
import re  # ✅ 부호 제거를 위한 모듈 추가

st.set_page_config(page_title="Korean-English Trainer", layout="centered")

st.title("🇰🇷 Korean-English Sentence Trainer 🇺🇸")

# 학습용 데이터 예시
data = pd.DataFrame({
    "Korean": [
        "시차 때문에 고생해본 적 있나요?",
        "외롭다고 느끼실 때가 있나요?",
        "널 위해 그것을 검색할계",
        "나는 여행가고 싶은 기분이야",
        "화장실이 어디인지 보여주시겠어요?",
        "살이 쪄서 속상해요",
        "간식을 먹고 싶어요",
        "저랑 영화 보러 가실래요?",
        "말을 행동으로 옮겨야 할 때야",
        "너 빨리 서둘러야 할 것 같아",
        "여행에서 비오는 날들 괜찮아",
        "커피 좀 마시려고요",
        "친구가 항상 절 놀려서 속상해요",
        "그가 우리에게 거짓말을 하지 않기를 바라요",
        "그녀는 취한 것 같아요",
        "영어 실력을 향상시키기 위해 컬컴에 가입할 거예요",
        "하루 종일 이걸 하고 있어",
        "네가 늦게 오면, 시작을 놓칠 거야",
        "네가 드디어 면허증을 따다니 기쁘다",
        "그는 같은 헬스장으로 다닌다고 말했어요",
        "나는 그런 상황에서 아니라고 말할 거야",
        "집에서 오전 5시 30분에 나와야 해",
        "셀카 찍는 것을 좋아해요",
        "제게 그 사진을 보여주시겠어요?",
        "우리집으로 와서 저녁 먹을래?",
        "이거 사기인 것 같아요",
        "내가 무슨 말을 할 수 있겠어?",
        "이거 나중에 합시다",
        "차이점이 뭔가요?",
        "근무 중에 온라인 쇼핑을 할 때도 있나요?",
        "같이 카페로 가는 거 어때요?",
        "그녀를 다시 만나면 같은 실수를 하지 않을 거예요",
        "이야기 들려줘서 고마워요",
        "만약 로또에 당첨되면 너에게 말 안해줄 거야",
        "쉬고 싶은 기분이다",
        "결정을 내려야 할 때야",
        "당신의 환대에 고마워요",
        "나는 당신에게 선물을 사줄 돈이 있어요",
        "그것을 편의점에서 사야 해요",
        "그들의 온라인 서비스는 정말  빨라",
        "그는 여자친구를 만들 것이라고 말했어요",
        "모든 일에 신경써줘서 고마워요",
        "설거지는 다 끝났어",
        "침착하려 노력하고 있어",
        "지하철을 탈 것 같아요",
        "너의 연락처가 어떻게 돼?",
        "그게 친구 좋다는 거야 (친구 좋다는게 이런거지)",
        "친구들과 놀 때 보통 노래방을 가요",
        "이 질문은 넘어가겠습니다",
        "어떻게 같은 실수를 또 저지를 수 있어?",
        "내일 제가 당신을 집에 데려다주고 싶어요",
        "내 실수를 인정하는 건 괜찮아",
        "라면을 좀 끓이려고요",
        "솔직히 난 그게 괜찮지 않아",
        "너는 그녀에게 사과해야해",
        "과거를 버려야 할 때야",
        "차여본 적 있나요?",
        "머리 염색하고 싶니?",
        "음식을 주문했었는데요, 맛 별로였어요",
        "너 병가내야 할 것 같아",
        "나 너무 피곤해서 집에 가서 쉬어야 할 것 같아",
        "내가 가장 좋아하는 책을 너에게 공유할게",
        "4시에 나 데리러 와줄 거야?",
        "그녀는 못 온다고 말했어요",
        "잔돈을 안 받았어요",
        "관심사가 뭐예요?",
        "침대 위에 누워있고 싶어요",
        "소리 좀 작게 해주시겠어요?",
        "평소에 운동은 하시나요?",
        "여행할 때 항상 사진을 SNS에 올려요",
        "그게 없어서 화가 나요",
        "내가 제일 좋아하는 장소를 소개할게",
        "네가 취직했다니 기쁘다",
        "그녀와 화해하려 하고 있어요",
        "거울을 얼마나 자주 보세요?",
        "부모님과는 얼마나 자주 이야기하시나요?",
        "그렇게 생각할 때도 있나요?",
        "멋진 카페에서 커피 마시고 싶어요",
        "물론이죠, 내가 처리할 수 있어요",
        "전 유튜브 보고 있어요, 왜냐면 심심하거든요",
        "저는 세계 도처에 여행할 거예요",
        "택시를 어디서 잡을 수 있나요?",
        "얼마나 자주 택시를 타고 집에 가나요?",
        "해외여행을 얼마나 자주 하시나요?",
        "평소에 그에게 먼저 문자는 하시나요?",
        "저는 조금 어색할 것 같아요",
        "더 오래 못 계신다니 안타까워요",
        "너에게 여행의 사진들을 보여줄게",
        "그게 내가 화가 난 이유야",
        "너의 감정들을 표현할 때야",
        "저는 5년 동안 같은 회사를 다니고 있어요",
        "당신에게 물어볼 것이 있어요",
        "시간이 정말 빨리 날아가는 것 같아요",
        "물론이죠, 다 먹을 수 있죠",
        "나는 노인들을 공경해야 해",
        "필라테스를 해 본 적 있어요?",
        "일찍 도착하면 카페에서 당신을 기다릴게요",
        "멍 때리는 것을 좋아해요",
        "통화는 다 끝났어",
        "지하철 역에 어떻게 가나요?",
        "잠이 올 것 같지 않아요",
        "니가 상처를 받았다니 안타깝다",
        "모르는 사람에게 말 걸어본 적 있나요?",
        "너 눈치 좀 채야할 것 같아",
        "그들이 그렇게 말했어요",
        "저는 20살 때부터 그 화장품을 써오고 있어요",
        "하나 추천해 줄래요?",
        "어떻게 너의 약속을 잊을 수 있어?",
        "난 그것이 성공적이어서 기쁘다",
        "뭘 드릴까요?",
        "담배 한대 피우고 싶어요",
        "만약 내일 비가 온다면 나는 실내에 머물 거야",
        "저는 집을 구하는 동안 이곳에 머물고 있어요",
        "난 네가 운전 시험에 떨어지지 않기를 받아",
        "그 영화가 별로였다는 것에 동의해요",
        "안됐지만 그는 내 취향이 아니었어",
        "가장 좋았던 어렸을적 기억은 뭐예요?",
        "건강해지기 위해 다이어트를 해요",
        "과제 언제 끝냈어?",
        "그를 어서 보고 싶어요",
        "너 좀 쉬어야겠다",
        "역에서 그녀를 데려올 거예요",
        "나는 나의 나쁜 습관을 고쳐야 해",
        "그가 제 전화를 안 받아서 속상해요",
        "당신이 간다면 저도 갈게요",
        "난 그녀가 나한테 답장 안해서 화가 나",
        "연습은 좀 하니?",
        "우리가 여행을 갈 수 있으면 좋겠어요",
        "수업을 빼먹고 싶니?",
        "나는 내가 더 나아지기 위해 노력 중이야",
        "내가 제안을 하나 할게",
        "요즘 점점 바빠지고 있어",
        "저는 더 저렴한 걸 살 거예요",
        "건설적인 비판은 괜찮아",
        "편의점에서 김밥 좀 사줄래요?",
        "나 혼자서 답을 알아내야겠어",
        "스스로에게 도전을 해야할 때야",
        "영어로 그걸 어떻게 말하나요?",
        "그에게 내 강아지 사진을 보여줄 거예요",
        "나 새로 나온 아이폰으로 폰 바꿀 거야",
        "드라이브하러 가는 것을 좋아해요",
        "뭔가 필요한게 있을 땐 온라인 쇼핑을 해요",
        "현금은 좀 가지고 다니시나요?",
        "당신의 충고에 동의해요",
        "막차를 잡기 위해 서둘렀어요",
        "저는 미래를 위해 저축할 거예요",
        "버스 대신 택시를 타는 건 어때요?",
        "그래서 너한테 물어봤던 거야",
        "그녀는 다음 달에 출장을 갈 거라고 했어요",
        "저랑 같이 가실래요?",
        "네가 나 좋아한 줄 몰랐어",
        "거기서 만날까요?",
        "몸이 좋지 않을 때 저는 잠을 자요",
        "시도해 보지 않으면 후회할 거예요",
        "다른 방법이 있어요",
        "당신이 허락한다면 제안을 하나 하고 싶어요",
        "이 가격이 맞는 것 같지 않아",
        "그녀는 곧 돌아올 거라고 했어요",
        "슬플 때는 초콜릿을 더 많이 먹어야 합니다",
        "미국에 가 본 적 있나요?",
        "일에 집중하기 위해 음악을 들어요",
        "너 절대로 포기하면 안돼",
        "너의 질문에 대답할 시간이야",
        "전 매일 컬컴에 가요, 왜냐면 저는 빨리 영어실력을 향상시키고 싶거든요",
        "공항까지 택시 같이 타고 가실래요?",
        "건강한 식습관이 관건이라는 것에 동의해요",
        "너 잠 좀 더 자야겠다",
        "나는 티비를 볼 때 채널을 많이 돌려요",
        "오늘은 제 생일이에요, 그래서 전 친구들로부터 많은 선물을 받았어요",
        "나는 커피를 줄이려 노력하고 있어",
        "나는 야채를 더 먹어야 해",
        "너의 걱정을 들어볼게",
        "이용 가능한 테이블이 없어요",
        "살빼기 위해 매일 적어도 두시간 운동해요",
        "그녀가 기차를 놓치지 않기를 바라요",
        "그거 한번 입어보고 싶어요",
        "아일랜드 음식 먹어본 적 있나요?",
        "수업에 집중하려고 노력 중이야",
        "어떻게 온 바닥에 물을 쏟을 수 있어?",
        "좀 더 크게 말해주실래요?",
        "너의 미래를 설계할 시간이야",
        "저는 그와 2년째 사귀고 있어요",
        "저 새로운 식당에 가보도록 합시다",
        "당신이 좋다면 알려주세요",
        "여기 아무것도 없어요",
        "다음에는 더 잘하고 싶어요",
        "집에 있을 땐 집안일을 해요",
        "평소에 늦게 일어날 때도 있나요?",
        "그녀는 절 위한 시간이 없다고 말했어요",
        "너 머리색 바꿀 거야?",
        "그녀를 혼자 두는게 좋겠어",
        "제 폰을 풀기 위해 지문을 등록했어요",
        "주스 한 잔만 가져다 주실래요?",
        "그것이 제가 그녀에 대해 좋아하는 부분이죠",
        "너 변명이 뭐야?",
        "내 목표로 점점 가까워지고 있어",
        "어떻게 카페를 못 찾을 수 있어?",
        "저라면 더 적게 마실 거예요",
        "종교가 어떻게 되세요?",
        "문제가 뭔가요?"

    ],
    "English": [
        "Have you ever suffered from jet lag?",
        "Do you ever feel alone?",
        "Let me search it for you",
        "I feel like going on a trip",
        "Will you show me where the restroom is?",
        "I am upset that I gained weight",
        "I feel like having a snack",
        "Will you go see the movie with me?",
        "It's time to translate words into action",
        "I think you should hurry up",
        "I'm ok with rainy day on trip",
        "I'm going to drink some coffee",
        "I am upset that my friend always teasys me ",
        "다음",
        "It seems that she is drunk",
        "I'm going to join Culcom to improve my English skill",
        "I have been doing this all day",
        "If you are late, You will miss the beginning",
        "I am happy that you finally got driver's license",
        "He said he goes to the same jym",
        "I would say no in that situation",
        "I have to leave my home at 5 30 am",
        "I like taking selfies",
        "Would you please show me the picture?",
        "Do you want to come to my home and have dinner?",
        "It seems that this is a scam",
        "What can I say ?",
        "Let's do this later",
        "What's the difference?",
        "Do you ever shop online at work?",
        "How about going to a cafe together?",
        "If I meet her again I will not make the same mistake",
        "Thank you for sharing the story",
        "If I win the lotery I will not tell you",
        "I feel like taking a rest",
        "It's time to make a decision",
        "Thank you for your warm welcome",
        "I have some money to buy you a present",
        "I should buy it at a convenience store",
        "I think their online service is very fast",
        "He said He would get a girlfriend",
        "Thank you for taking care of everything",
        "I am done with the dishes",
        "I'm trying to stay calm",
        "I would take the subway",
        "What's your phone number?",
        "That's what freinds are for",
        "When I hang out with my friends , I usally go to a Karaoke",
        "I am going to skip this question",
        "How could you make the same mistake again",
        "I hope to walk you home tomorrow",
        "I'm ok with admitting my mistake",
        "I'm going to cook some ramen",
        "I'm not ok with that to be honest",
        "I think you should  apologize to her",
        "It's time to let go of the past",
        "Have you ever dumped?",
        "Do you want to get your hair dyed?",
        "I orderd food, but it didn't taste good",
        "I think you should call in sick",
        "I should go home and rest because I'm so tired",
        "Let me share my favorite book with you",
        "Will you pick me up at 4 pm?",
        "She said she couldn't come",
        "I didn't get my change",
        "What's your interested?",
        "I feel like laying in bed",
        "Will you turn down the volume?",
        "Do you ever exercise?",
        "When I travel, I always post pictures to SNS",
        "I am upset that I don't have it",
        "Let me show you my favorite spot",
        "I am happy that you get a job",
        "I'm trying to make up with her",
        "How often do you look in the mirror?",
        "How often do you talk to your parents?",
        "Do you ever think like that?",
        "I feel like drinking some coffee at a nice cafe",
        "Sure, I can handle it",
        "I am watching Yootube, because I am bored",
        "I would trable all over the world",
        "Where can I get a taxi?",
        "How often do you take a taxi home?",
        "How often do you trevel abroad?",
        "Do you ever text to him first?",
        "I would feel a little awkward",
        "I am sorry that you can't stay longer",
        "Let me show you pictures of the trip",
        "That's why I'm upset",
        "It's time to express your feelings",
        "I have been working for the same company for 5 years",
        "I have a something to ask",
        "I think time really flies",
        "Sure, I can finish the food",
        "I should respect the elderly",
        "Have you ever done pilates?",
        "If I arrived early, I will wait for you at the cafe",
        "I like spacing out",
        "I am done with my phone call",
        "How can I get to the subway station?",
        "I don't think I can fall asleep",
        "I am sorry that you got hurt",
        "Have you ever started talking to a stranger?",
        "I think you shound take a hint",
        "That's what they said",
        "I have been useing the cosmetics since I was 20",
        "Can you recommand me one?",
        "How could you forget your promise",
        "I am glad that it was successful",
        "What can I get you?",
        "I feel like smoking a cigarette",
        "If it rains tomorrow, I will just stay indoors",
        "I have been staying here while house - hunting",
        "I hope that  you don't the fail driving test",
        "I agree that the movie was not good",
        "I am sorry that he was not my type",
        "What's your favorite chlidhood memory?",
        "I am on a diet to be healthy",
        "When did you finish your assignment?",
        "I hope to see him soon",
        "I think you should rest",
        "I'm going to get her from the station",
        "I should fix my bad habits",
        "I am upset that he didn't answer my call",
        "If you are going I will go",
        "I am upset that she didn't reply to me",
        "Do you ever practice?",
        "I hope that we can go on a trip",
        "Do you want to cut classes?",
        "I'm trying to get better",
        "Let me make a suggestion",
        "I am getting busier nowadays",
        "I would get a chipper one",
        "I'm ok with constructive criticism",
        "Will you buy me a gimbap from a convenience store?",
        "I have to find the answer by myself",
        "It's time to challange yourself",
        "How can I say that in English?",
        "I'm going to show him pictures of my dog",
        "I'm going to change my phone to the new I-phone",
        "I like going for a drive",
        "When I need something, I shop online",
        "Do you ever carry cash?",
        "I agree with your advice",
        "I hurried to catch the last bus",
        "I would save the money for the future",
        "How about taking a taxi instead of a bus",
        "That's why I asked you",
        "She said  she will go on a business trip next month",
        "Will you come with me?",
        "I didn't know you liked me",
        "Will you meet me there?",
        "When I don't feel well, I get some sleep",
        "If I don't try I will regret it",
        "There is a another way",
        "If you allow, I'd like to make a suggestion",
        "I don't think this price is right",
        "She said she will come back soon",
        "When you are sad, we should eat more chocholate",
        "Have you ever been to the USA",
        "I listen to music to focus on my work",
        "I think you should never give up",
        "It's time to answer your question ",
        "I go to the culcom everyday, because I want to improve my Engish skills quickly",
        "Do you want to share a cab to the airport?",
        "I agree that eating healty is the key.",
        "I think you should sleep more",
        "When I watch TV, I switched the channel a lot",
        "Today is my birthday, so I got many gifts from friends",
        "I'm trying to cut down on coffee",
        "I should eat more vegitables",
        "Let me listen to your concerns",
        "There is no tables available",
        "I work out every day for at least  two hours to lose weight",
        "I hope that she doesn't miss the train",
        "I'd like to try it on",
        "Have you ever tried irish food",
        "I'm trying to focus on my class",
        "How could you spill the water all over the floor",
        "Will you speak louder, please?",
        "It's time to plan your future ",
        "I have been dating him for 2 years",
        "Let's try that new restaurant",
        "If you like it, let me know",
        "There is nothing here",
        "I hope to get better next time",
        "When I stay at home, I do my house chores",
        "Do you ever get up late?",
        "She said she had no time for me",
        "Will you change your hair color?",
        "I think you should leave her alone",
        "I registered my finger print to unlock my phone",
        "Would you please bring me a glass of juice?",
        "That's what I like about her",
        "What's your excuse?",
        "I am getting closer to my goal",
        "How could you not find the cafe",
        "I would drink less",
        "What's your religion?",
        "What's the problem?"
    ]
})

# ✅ 상태 초기화
if 'current_row' not in st.session_state:
    st.session_state.current_row = None
if 'answered' not in st.session_state:
    st.session_state.answered = False
if 'feedback' not in st.session_state:
    st.session_state.feedback = ""
if 'first_try_correct' not in st.session_state:
    st.session_state.first_try_correct = set()
if 'attempt_count' not in st.session_state:
    st.session_state.attempt_count = {}
if 'input_key' not in st.session_state:
    st.session_state.input_key = 0  # ✅ 입력창 리셋을 위한 key 값

# ✅ 아직 안 맞춘 문장 인덱스만 선택
available_indices = [
    i for i in range(len(data))
    if i not in st.session_state.first_try_correct
]

# ✅ 모든 문장을 맞춘 경우
if not available_indices:
    st.success("🎉 한 번에 모든 문장을 맞추셨어요! 대단해요!")
else:
    # ✅ Next 클릭 시 입력창도 완전 초기화
    if st.session_state.current_row is None or st.button("🔁 Next Random Sentence"):
        st.session_state.current_row = random.choice(available_indices)
        st.session_state.answered = False
        st.session_state.feedback = ""
        st.session_state.input_key += 1  # ✅ 입력창 초기화 트리거

    # ✅ 현재 문장 설정
    korean_sentence = data.iloc[st.session_state.current_row]['Korean']
    english_answer = data.iloc[st.session_state.current_row]['English']
    st.markdown(f"### 🇰🇷 {korean_sentence}")

    # ✅ 입력 + 엔터 제출
    with st.form(key="answer_form"):
        user_input = st.text_input(
            "✍️ Type your English translation:",
            key=f"user_input_{st.session_state.input_key}"  # ✅ key만 사용해 입력창 리셋
        )
        submitted = st.form_submit_button("✅ Check Answer")

        if submitted and not st.session_state.answered:
            st.session_state.attempt_count.setdefault(st.session_state.current_row, 0)
            st.session_state.attempt_count[st.session_state.current_row] += 1

            def normalize(text):
                return re.sub(r'[^a-zA-Z0-9 ]', '', text.lower().strip())

            if normalize(user_input) == normalize(english_answer):
                if st.session_state.attempt_count[st.session_state.current_row] == 1:
                    st.session_state.first_try_correct.add(st.session_state.current_row)
                st.session_state.feedback = "✅ Correct! Well done."
            else:
                st.session_state.feedback = f"❌ Incorrect. Correct answer: **{english_answer}**"
            st.session_state.answered = True

    # ✅ 피드백 표시
    if st.session_state.feedback:
        st.info(st.session_state.feedback)